# Generated by Django 3.0.11 on 2021-10-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
